/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.gui;

import com.esprit.dao.OffreDAO;
import com.esprit.dao.UserDAO;
import com.esprit.gui.Login;
import com.esprit.entities.Offre;
import com.esprit.entities.User;
import static com.esprit.gui.Login.us;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import static java.lang.String.*;
import static java.lang.String.format;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.Element;
import javax.swing.table.AbstractTableModel;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author maher
 */
public class Afficher_annonce extends javax.swing.JFrame {

   byte[] p1;
    byte[] p2;
    byte[] p3;
   

    /**
     * Creates new form AjouterOffre
     */
    public Afficher_annonce() {
        initComponents();
        affichage();
        update_table();

    }
     public static boolean isInteger(String s) {

        boolean v = false;
        try {
            Integer.parseInt(s);
            v = true;
        } catch (Exception e) {
            v = false;
        }
        return v;
    }
     public static boolean isFloat(String s) {

        boolean v = false;
        try {
            Float.parseFloat(s);
            v = true;
        } catch (Exception e) {
            v = false;
        }
        return v;
    }
    

    private void affichage() {
        String s = Login.login.getText();
//            User ut = new User();
//            UserDAO dao = new UserDAO();
//            ut = dao.findUserByLogin(s);
        bienvenu.setText("Bienvenue  " + us.getPrenom() + " " + us.getNom());
        

    }

    private void update_table() {
//        User ut = new User();
        UserDAO dao = new UserDAO();
        // us = dao.findUserByLogin(Login.login.getText());
        int id =Login.us.getId();
        //System.out.println(id);
        OffreDAO d = new OffreDAO();
        
        d.update_tableorg(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nbre_piece = new javax.swing.JComboBox();
        type = new javax.swing.JComboBox();
        code_postal = new javax.swing.JTextField();
        gouvernorat = new javax.swing.JComboBox();
        prix = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        superficie = new javax.swing.JTextField();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        titre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        delegation = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bienvenu = new javax.swing.JLabel();
        datedebut = new com.toedter.calendar.JDateChooser();
        datefin = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrg = new javax.swing.JTable();
        localite = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        arriere = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nbre_piece.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S+1", "S+2", "S+3", "S+4" }));
        getContentPane().add(nbre_piece);
        nbre_piece.setBounds(210, 240, 160, 20);

        type.setEditable(true);
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "chambre", "maison" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type);
        type.setBounds(210, 220, 160, 20);
        getContentPane().add(code_postal);
        code_postal.setBounds(200, 480, 150, 20);

        gouvernorat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ariana", "Beja", "Ben Arous", "Bizerte", "Gabes", "Gafsa", "Jendouba", "Kairouan", "Gasserine", "Kebili", "Le kef", "Mahdia", "Manouba", "Medenine", "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliabe", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouane" }));
        getContentPane().add(gouvernorat);
        gouvernorat.setBounds(10, 430, 140, 20);

        prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixActionPerformed(evt);
            }
        });
        getContentPane().add(prix);
        prix.setBounds(210, 300, 160, 20);

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 330, 150, 70);

        superficie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superficieActionPerformed(evt);
            }
        });
        getContentPane().add(superficie);
        superficie.setBounds(210, 270, 160, 20);

        modifier.setText("modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier);
        modifier.setBounds(630, 370, 120, 23);

        supprimer.setText("supprimer");
        supprimer.setActionCommand("s");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer);
        supprimer.setBounds(1010, 370, 120, 23);

        titre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(titre);
        titre.setBounds(210, 190, 160, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setText("Description");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 340, 100, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(424, 600, 290, 40);
        getContentPane().add(delegation);
        delegation.setBounds(200, 430, 160, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/4.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 623, 103, 80);
        getContentPane().add(bienvenu);
        bienvenu.setBounds(590, 20, 230, 50);
        getContentPane().add(datedebut);
        datedebut.setBounds(160, 540, 170, 20);

        datefin.setMaximumSize(new java.awt.Dimension(100, 100));
        datefin.setPreferredSize(new java.awt.Dimension(60, 20));
        getContentPane().add(datefin);
        datefin.setBounds(490, 540, 200, 20);

        tableOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrgMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableOrgMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableOrg);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(540, 80, 660, 240);

        localite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localiteActionPerformed(evt);
            }
        });
        getContentPane().add(localite);
        localite.setBounds(420, 430, 160, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Titre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 190, 80, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 220, 50, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Nombre de pièce");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 240, 120, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Superficie");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 270, 80, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Prix");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 310, 50, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Gouvernorat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 410, 100, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Délégation");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 410, 100, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Localité");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 410, 70, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Code postal");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 480, 100, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Date début");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 540, 90, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Date fin");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(400, 540, 70, 17);

        arriere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/arriere plan.jpg"))); // NOI18N
        getContentPane().add(arriere);
        arriere.setBounds(0, 0, 1440, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localiteActionPerformed

    }//GEN-LAST:event_localiteActionPerformed

    private void superficieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superficieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_superficieActionPerformed

    private void prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixActionPerformed


    private void tableOrgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrgMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tableOrgMouseReleased

    private void tableOrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrgMouseClicked
        int index = tableOrg.getSelectedRow();
        
       
        String Table_click = (tableOrg.getModel().getValueAt(index, 0).toString());
        if (index > -1) {
            Offre et = new Offre();
            int id = (int) tableOrg.getValueAt(index, 0);
            OffreDAO dao = new OffreDAO();
            
            et = dao.rechercherOffreById(id);
            System.out.println(et.getTitre());
            titre.setText(et.getTitre());
            description.setText(et.getDescription());
            delegation.setText(et.getDelegation());
            localite.setText(et.getLocalite());

            String add;
            add = Float.toString(et.getSuperFicie());
            superficie.setText(add);

            String a;
            a = Float.toString(et.getPrix());
            prix.setText(a);

            String b;
            b = Integer.toString(et.getCodePostal());
            code_postal.setText(b);

            datedebut.setDate(et.getDateDebut());
            datefin.setDate(et.getDateFin());
            String ch="";
            System.out.println(et.getType());
            if(et.getType()==0)
                ch="chambre";
            else ch="Maison";
            //type.addItem(ch);
             gouvernorat.addItem(et.getGouvernorat());
//    int   nb=et.getNbrepiece();
//    if (nb==1){
//        type.setToolTipText("chambre");
//    }
//    else 
//         type.setToolTipText("maison");
           
       
//            format = new ImageIcon(et.getPhoto1());
//            photo1.setIcon(format);}

             int choix = type.getSelectedIndex();
        int bb = 0;
        String cat;
        switch (choix) {
            case 0:
                cat="chambre";
               // bb = 0;
                break;
            case 1:
                cat="maison";
               // bb = 1;
                break;

        }
       
             
             
    }//GEN-LAST:event_tableOrgMouseClicked
}
    
    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        
        
       boolean test2;
        Offre e = new Offre();
         int index = tableOrg.getSelectedRow();
        int id1 = (int) tableOrg.getValueAt(index, 0);

         if(prix.getText().equals("")||titre.getText().equals("")||superficie.getText().equals("")||localite.getText().equals("")||delegation.getText().equals("")||code_postal.getText().equals("") )
        
         {
             jLabel1.setText("vous devez remplir tous les champs");
         }
        
        
         else {
             if (!isFloat(superficie.getText())||!isFloat(prix.getText())){
                 jLabel1.setText("verifiez la superficie ou le prix ");}
        
         if(!isInteger(code_postal.getText())) {

        jLabel1.setText("verifiez le code postal ");}
         
      
             
         
         
          if(isFloat(prix.getText())&& isFloat(superficie.getText()))
        
                 {
        
        
       
        e.setTitre(titre.getText());
        e.setDelegation(delegation.getText());
        e.setLocalite(localite.getText());
        e.setDescription(description.getText());
        e.setCodePostal(Integer.parseInt(code_postal.getText()));
        e.setSuperFicie(Float.parseFloat(superficie.getText()));
        e.setGouvernorat(gouvernorat.getSelectedItem().toString());
        e.setPrix(Float.parseFloat(prix.getText()));
        java.util.Date utilDate = datedebut.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        e.setDateDebut(sqlDate);

        java.util.Date utilDate2 = datefin.getDate();
        java.sql.Date sqlDate2 = new java.sql.Date(utilDate2.getTime());
        e.setDateFin(sqlDate2);

        //e.setDateDebut((datedebut.getDate));
        // e.setDateFin((datefin.getSelectedItem().toString()));
        int t = type.getSelectedIndex();
        int bb = 0;
        switch (t) {
            case 0:

                bb = 0;
                break;
            case 1:

                bb = 1;
                break;

        }
        e.setType(bb);;

        int b = nbre_piece.getSelectedIndex();
        int nb = 0;
        switch (b) {
            case 0:
                nb = 1;
                break;
            case 1:
                nb = 2;
                break;
            case 2:
                nb = 3;
                break;
            case 3:
                nb = 4;
                break;
        }
        e.setNbrepiece(nb);

        e.setGouvernorat(gouvernorat.getSelectedItem().toString());

//test = od.deleteOffre(id);
        OffreDAO d = new OffreDAO();
      
        int confirm = JOptionPane.showConfirmDialog(this, "Etes vous sur de modifier votre annonce!!!", "Confirmation", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null);
        if (confirm == JOptionPane.OK_OPTION) {
          test2 = d.modifierOffre(e, id1);
          InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\modification.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);

                    }
        JOptionPane.showMessageDialog(null, " annonce modifiée");

        update_table();
        titre.setText(null);
        superficie.setText(null);
        prix.setText(null);
        description.setText(null);
        datedebut.setDate(null);
        datefin.setDate(null);
        localite.setText(null);
        delegation.setText(null);
        code_postal.setText(null);
                 }            
                 }
    } 
        
       
    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed

// TODO add your handling code here:
        boolean test;
        OffreDAO od = new OffreDAO();

        int index = tableOrg.getSelectedRow();
        int id = (int) tableOrg.getValueAt(index, 0);
        
         int confirm = JOptionPane.showConfirmDialog(this, "Etes vous sur de supprimer votre annonce!!!", "Confirmation", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null);
        if (confirm == JOptionPane.OK_OPTION) {
            test = od.deleteOffre(id);
          InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\suppression.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);

                    }
     

        JOptionPane.showMessageDialog(null, " annonce supprimée");
        update_table();
        titre.setText(null);
        superficie.setText(null);
        prix.setText(null);
        description.setText(null);
        localite.setText(null);
        delegation.setText(null);
        code_postal.setText(null);
        datedebut.setDate(null);
        datefin.setDate(null);
    }
    }//GEN-LAST:event_supprimerActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
//         InputStream in;
//                    try {
//                        in = new FileInputStream(new File("‪C:\\Claro.wav"));
//                        AudioStream audios = new AudioStream(in);
//                        AudioPlayer.player.start(audios);
//                    } catch (Exception ex) {
//                        JOptionPane.showMessageDialog(null, ex);
//
//                    }
//            
        
        
        
        
        menu menu = new menu() ;
       menu.setVisible(true);
       
       menu.setSize(1175, 728);
       menu.setLocationRelativeTo(null);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Afficher_annonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Afficher_annonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Afficher_annonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Afficher_annonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Afficher_annonce an = new Afficher_annonce();
                an.setVisible(true);
                an.setSize(1175, 728);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arriere;
    private javax.swing.JLabel bienvenu;
    private javax.swing.JTextField code_postal;
    private com.toedter.calendar.JDateChooser datedebut;
    private com.toedter.calendar.JDateChooser datefin;
    private javax.swing.JTextField delegation;
    private javax.swing.JTextArea description;
    private javax.swing.JComboBox gouvernorat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField localite;
    private javax.swing.JButton modifier;
    private javax.swing.JComboBox nbre_piece;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField superficie;
    private javax.swing.JButton supprimer;
    public static javax.swing.JTable tableOrg;
    private javax.swing.JTextField titre;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
//private ImageIcon format=null;
//byte[] person_image=null;

}
