/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.gui;

import com.esprit.dao.OffreDAO;
import com.esprit.dao.UserDAO;

import com.esprit.entities.Offre;
import static com.esprit.gui.Login.us;

import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import static java.lang.String.*;
import static java.lang.String.format;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Date;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.Element;
import sun.audio.AudioPlayer;
import static sun.audio.AudioPlayer.player;
import sun.audio.AudioStream;

/**
 *
 * @author maher
 */
public class Ajouter_offre extends javax.swing.JFrame {
    
   
   

    byte[] p1;
    byte[] p2;
    byte[] p3;
    
    private String filename;
    private String filename1;
    private String filename2;
   
    /**
     * Creates new form AjouterOffre
     */
    public Ajouter_offre()  {
        initComponents();
//       UIManager.setLookAndFeel(new SyntheticaAluOxideLookAndFeel());

    }
    
     public static boolean isInteger(String s) {

        boolean v = false;
        try {
            Integer.parseInt(s);
            v = true;
        } catch (Exception e) {
            v = false;
        }
        return v;
    }
public static boolean isFloat(String s) {

        boolean v = false;
        try {
            Float.parseFloat(s);
            v = true;
        } catch (Exception e) {
            v = false;
        }
        return v;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nbre_piece = new javax.swing.JComboBox();
        type = new javax.swing.JComboBox();
        code_postal = new javax.swing.JTextField();
        gouvernorat = new javax.swing.JComboBox();
        prix = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        superficie = new javax.swing.JTextField();
        titre = new javax.swing.JTextField();
        delegation = new javax.swing.JTextField();
        datedebut = new com.toedter.calendar.JDateChooser();
        reponse = new javax.swing.JTextField();
        datefin = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        localite = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        arriere = new javax.swing.JLabel();
        selectionner1 = new javax.swing.JButton();
        selectionner2 = new javax.swing.JButton();
        selectionner3 = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nbre_piece.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S+1", "S+2", "S+3", "S+4" }));
        getContentPane().add(nbre_piece);
        nbre_piece.setBounds(230, 340, 280, 30);

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "chambre", "maison" }));
        getContentPane().add(type);
        type.setBounds(230, 290, 280, 30);
        getContentPane().add(code_postal);
        code_postal.setBounds(784, 405, 276, 32);

        gouvernorat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ariana", "Beja", "Ben Arous", "Bizerte", "Gabes", "Gafsa", "Jendouba", "Kairouan", "Gasserine", "Kebili", "Le kef", "Mahdia", "Manouba", "Medenine", "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliabe", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouane" }));
        getContentPane().add(gouvernorat);
        gouvernorat.setBounds(790, 230, 270, 30);

        prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixActionPerformed(evt);
            }
        });
        getContentPane().add(prix);
        prix.setBounds(244, 470, 276, 30);

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 540, 250, 80);

        superficie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superficieActionPerformed(evt);
            }
        });
        getContentPane().add(superficie);
        superficie.setBounds(244, 406, 276, 32);

        titre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(titre);
        titre.setBounds(235, 230, 276, 30);
        getContentPane().add(delegation);
        delegation.setBounds(784, 290, 276, 30);
        getContentPane().add(datedebut);
        datedebut.setBounds(780, 460, 280, 30);
        getContentPane().add(reponse);
        reponse.setBounds(1430, 560, 180, 20);

        datefin.setMaximumSize(new java.awt.Dimension(100, 100));
        datefin.setPreferredSize(new java.awt.Dimension(60, 20));
        getContentPane().add(datefin);
        datefin.setBounds(780, 510, 280, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(780, 324, 270, 20);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 510, 270, 20);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 270, 270, 20);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(774, 380, 280, 20);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(784, 444, 280, 20);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 444, 270, 20);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(784, 490, 270, 20);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(820, 664, 330, 30);

        localite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localiteActionPerformed(evt);
            }
        });
        getContentPane().add(localite);
        localite.setBounds(784, 346, 276, 32);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/4.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 640, 80, 80);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(784, 540, 270, 20);

        arriere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/formulaire ajouter offre.png"))); // NOI18N
        getContentPane().add(arriere);
        arriere.setBounds(0, 0, 1165, 728);

        selectionner1.setText("ajout1");
        selectionner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selectionner1MouseReleased(evt);
            }
        });
        selectionner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionner1ActionPerformed(evt);
            }
        });
        getContentPane().add(selectionner1);
        selectionner1.setBounds(750, 570, 150, 40);

        selectionner2.setText("ajout2");
        selectionner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionner2ActionPerformed(evt);
            }
        });
        getContentPane().add(selectionner2);
        selectionner2.setBounds(930, 570, 140, 40);

        selectionner3.setText("ajout3");
        selectionner3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionner3ActionPerformed(evt);
            }
        });
        getContentPane().add(selectionner3);
        selectionner3.setBounds(840, 620, 140, 40);

        ajouter.setText("ajouter");
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ajouterMouseReleased(evt);
            }
        });
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter);
        ajouter.setBounds(420, 640, 380, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localiteActionPerformed

    }//GEN-LAST:event_localiteActionPerformed

    private void superficieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superficieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_superficieActionPerformed

    private void prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterActionPerformed

    private void ajouterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseReleased
        // TODO add your handling code here:
        int test = 0;
        //prix.setText("");
      Offre e = new Offre();
//         
         if (prix.getText().equals("")) {
               jLabel2.setText("vous devez taper un prix");
            } 
         else  if (!isFloat(prix.getText())){
                jLabel2.setText("verfiez votre prix ");}
             else{
             
        e.setPrix( Float.parseFloat(prix.getText()));
           test++;
         }
         
        if (titre.getText().equals("")) {
              jLabel1.setText("vous devez taper un titre");
            } else {
                if (isInteger(titre.getText())) {
                     jLabel1.setText("verifiez votre titre");
                } else {
                     e.setTitre(titre.getText());
                    test++;
                }
        }
        
//        if (p1==null||p2==null||p3==null) {
//            jTextField6.setText("ajouter  3  images");
//            } 
//                 else {
//                      e.setPhoto1(p1);
//        e.setPhoto2(p2);
//        e.setPhoto3(p3);
//                    test++;
//                    
//                }
//        
        
        
      if(datefin.getCalendar()  == null)
      {      jLabel8.setText("ajoutez date fin");  } 
           
      else{     
             java.util.Date utilDate = datefin.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        e.setDateFin(sqlDate);
            test++;
      }
      
      if(datedebut.getCalendar()  == null)
      {      jLabel7.setText("ajoutez date debut");  } 
           
      else{     
             java.util.Date utilDate1 = datedebut.getDate();
        java.sql.Date sqlDate1 = new java.sql.Date(utilDate1.getTime());
        e.setDateDebut(sqlDate1);
            test++;
      }
//      
      
      
            
         if (superficie.getText().equals("")) {
                jLabel3.setText("vous devez taper une superficie");
            } 
         else {
             if (!isFloat(superficie.getText())){
                  jLabel3.setText(" verifiez la superficie");}
             else{
             
        
        e.setSuperFicie(Float.parseFloat(superficie.getText()));
             test++; 
         }
       
             
         }       
            
          if (localite.getText().equals("")) {
                 jLabel5.setText("vous devez taper une localité");
            } else {
                if (isInteger(localite.getText())) {
                     jLabel5.setText("verifiez la localité");
                } else {
                     e.setLocalite(localite.getText());
                    test++;
                }
        }
          
          if(p1!=null ||p2!=null||p3!=null){
              e.setPhoto1(p1);
       e.setPhoto2(p2);
        e.setPhoto3(p3);  
           test++;
          }
          else{
               jLabel9.setText("ajouter au moins une photo");
          }
         
           if (delegation.getText().equals("")) {
                 jLabel4.setText("vous devez taper une delegation ");
            } else {
                if (isInteger(delegation.getText())) {
                     jLabel4.setText("verifiez la delegation");
                } else {
                     e.setLocalite(delegation.getText());
                    test++;
                }
        }
          
          
          
          if (code_postal.getText().equals("")) {
                jLabel6.setText("vous devez taper uun code postal");
            } 
         else {
             if (!isInteger(code_postal.getText())){
                  jLabel6.setText(" verifiez votre code postal");}
             else{
             
        
      
        e.setCodePostal(Integer.parseInt(code_postal.getText()));
             test++; 
         }
       
             
         }       
            
          if (test == 9)     {
         
//          java.util.Date utilDate = datedebut.getDate();
//        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
//        e.setDateDebut(sqlDate);
//        java.util.Date utilDate2 = datefin.getDate();
//        java.sql.Date sqlDate2 = new java.sql.Date(utilDate2.getTime());
//        e.setDateFin(sqlDate2);
//            e.setPhoto1(p1);
//        e.setPhoto2(p2);
//        e.setPhoto3(p3);
        e.setDescription(description.getText());
        
         int b = nbre_piece.getSelectedIndex();
        int nb = 0;
        switch (b) {
            case 0:
                nb = 1;
                break;
            case 1:
                nb = 2;
                break;
            case 2:
                nb = 3;
                break;
            case 3:
                nb = 4;
                break;
        }
         e.setNbrepiece(nb);
         
           

        e.setLocalite(localite.getText());

       

        int choix = type.getSelectedIndex();
        int bb = 0;
        switch (choix) {
            case 0:

                bb = 0;
                break;
            case 1:

                bb = 1;
                break;

        }
        e.setType(bb);

        int ch = gouvernorat.getSelectedIndex();
        String cat = "ariana";
        switch (ch) {
            case 0:
                cat = "Ariana";
                break;
            case 1:
                cat = "Beja";
                break;
            case 2:
                cat = "Ben Arous";
                break;
            case 3:
                cat = "Bizerte";
                break;
            case 4:
                cat = "Gabes";
                break;
            case 5:
                cat = "Gafsa";
                break;
            case 6:
                cat = "Jendouba";
                break;
            case 7:
                cat = "kairouan";
                break;
            case 8:
                cat = " kasserine ";
                break;
            case 9:
                cat = "kebili";
                break;
            case 10:
                cat = "le kef";
                break;
            case 11:
                cat = "Mahdia";
                break;
            case 12:
                cat = "Manouba";
                break;
            case 13:
                cat = "Medenine";
                break;
            case 14:
                cat = "Monastir";
                break;
            case 15:
                cat = "Nabeul";
                break;
            case 16:
                cat = "Sfax";
                break;
            case 17:
                cat = "Sidi Bouzid";
                break;
            case 18:
                cat = " Siliane";
                break;
            case 19:
                cat = "Sousse";
                break;
            case 20:
                cat = " Tataouine";
                break;
            case 21:
                cat = "  Tozeur";
                break;
            case 22:
                cat = "tunis";
                break;
            case 23:
                cat = "zaghouene";
                break;

            default:
                cat = "";

        }
        e.setGouvernorat(cat);

        e.setDelegation(delegation.getText());

       
       
//        String s = (String) e.getPrix();
        int id5 = Login.us.getId();
        OffreDAO dao = new OffreDAO();
        //String ch1 = e.getPrix()+"";
//        if(ch1.equals("") ||titre.equals("")||e.getDescription().equals("")||e.getLocalite().equals("")||e.getDelegation().equals(""))
//    {
//    JOptionPane.showMessageDialog(rootPane,"ajout des variables");
//        
//    }else {
        int confirm = JOptionPane.showConfirmDialog(this, "Etes vous sur de publier cette annonce sur notre site !!!", "Confirmation", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null);
        if (confirm == JOptionPane.OK_OPTION) {
        dao.ajouterOffre(e,id5);
        //JOptionPane.showMessageDialog(rootPane,"vous voulez ajouté");
          JOptionPane.showMessageDialog(rootPane," annonce ajoutée");
         
             InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\annonce_ajoutee.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);

                    }
            
             
//        
//   
//    
//         
//          
//        
//        
//          else { 
//        
    

     
        //System.out.println(prix.getText());
     

        
      
        }
            
            
             
//        
//   
//    
//         
//          
//        
//        
//          else { 
//        
    

     
        //System.out.println(prix.getText());
     

        
      

       
      
          }
      
        
    }//GEN-LAST:event_ajouterMouseReleased

        

    private void selectionner1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectionner1MouseReleased
        // TODO add your handling code here

    }//GEN-LAST:event_selectionner1MouseReleased


    private void selectionner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionner1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);

        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        System.out.println("path=" + filename);
        Path path = Paths.get(filename);

        try {
            File image = new File(filename);

            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();

            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            p1 = bos.toByteArray();
            System.out.println("photo ajoutée");
        } catch (Exception ex) {

        }


    }//GEN-LAST:event_selectionner1ActionPerformed

    private void selectionner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionner2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);

        File f = chooser.getSelectedFile();
        filename1 = f.getAbsolutePath();
        System.out.println("path=" + filename1);
        Path path1 = Paths.get(filename1);

        try {
            File image = new File(filename1);

            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();

            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            p2 = bos.toByteArray();
            System.out.println("photo ajoutée");
        } catch (Exception ex) {

        }

    }//GEN-LAST:event_selectionner2ActionPerformed

    private void selectionner3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionner3ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);

        File f = chooser.getSelectedFile();
        filename2 = f.getAbsolutePath();
        System.out.println("path=" + filename2);
        Path path2 = Paths.get(filename2);

        try {
            File image = new File(filename2);

            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();

            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            p3 = bos.toByteArray();
            System.out.println("photo ajoutée");
        } catch (Exception ex) {
           

        }

    }//GEN-LAST:event_selectionner3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
//         InputStream in;
//                    try {
//                        in = new FileInputStream(new File("‪C:\\Claro.wav"));
//                        AudioStream audios = new AudioStream(in);
//                        AudioPlayer.player.start(audios);
//                    } catch (Exception ex) {
//                        JOptionPane.showMessageDialog(null, ex);
//
//                    }
//            
        
        
        
        
        menu menu = new menu() ;
       menu.setVisible(true);
       
       menu.setSize(1175, 728);
       menu.setLocationRelativeTo(null);
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajouter_offre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajouter_offre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajouter_offre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajouter_offre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//              
                    Ajouter_offre an = new Ajouter_offre();
//              
                    an.setVisible(true);
                    an.setSize(1175, 728);
                    an.setLocationRelativeTo(null);
//               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JLabel arriere;
    private javax.swing.JTextField code_postal;
    private com.toedter.calendar.JDateChooser datedebut;
    private com.toedter.calendar.JDateChooser datefin;
    private javax.swing.JTextField delegation;
    private javax.swing.JTextArea description;
    private javax.swing.JComboBox gouvernorat;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localite;
    private javax.swing.JComboBox nbre_piece;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField reponse;
    private javax.swing.JButton selectionner1;
    private javax.swing.JButton selectionner2;
    private javax.swing.JButton selectionner3;
    private javax.swing.JTextField superficie;
    private javax.swing.JTextField titre;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables

}
