/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.gui;

import com.esprit.dao.OffreDAO;
import com.esprit.entities.Offre;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author maher
 */
public class conversation extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public conversation() {
        initComponents();
        Affiche();
    }

    public void Affiche() {

        int id = (int) (Math.random() * (6)) + 1;
        int id2, id3, id4, id5, id6;
        do {
            id2 = (int) (Math.random() * (6)) + 1;
        } while (id2 == id);
        do {
            id3 = (int) (Math.random() * (6)) + 1;
        } while (id3 == id || id3 == id2);
        do {
            id4 = (int) (Math.random() * (6)) + 1;
        } while (id4 == id || id4 == id2 || id4 == id3);
        do {
            id5 = (int) (Math.random() * (6)) + 1;
        } while (id5 == id || id5 == id2 || id5 == id3 || id5 == id4);
        do {
            id6 = (int) (Math.random() * (6)) + 1;
        } while (id6 == id || id6 == id2 || id6 == id3 || id6 == id4 || id6 == id5);
        
        
        OffreDAO od = new OffreDAO();
        Offre o = new Offre();
        o = od.rechercherOffreById(id);
        byte[] img = o.getPhoto1();
        ImageIcon icon = new ImageIcon(img);
        annonce1.setIcon(icon);

        OffreDAO od1 = new OffreDAO();
        Offre o1 = new Offre();
        o1 = od1.rechercherOffreById(id2);
        byte[] img1 = o1.getPhoto1();
        ImageIcon icon1 = new ImageIcon(img1);
        annonce2.setIcon(icon1);

        OffreDAO od2 = new OffreDAO();
        Offre o2 = new Offre();
        o2 = od2.rechercherOffreById(id3);
        byte[] img2 = o2.getPhoto1();
        ImageIcon icon2 = new ImageIcon(img2);
        annonce3.setIcon(icon2);

        OffreDAO od3 = new OffreDAO();
        Offre o3 = new Offre();
        o3 = od3.rechercherOffreById(id4);
        byte[] img3 = o3.getPhoto1();
        ImageIcon icon3 = new ImageIcon(img3);
        annonce4.setIcon(icon3);// NOI18N

//OffreDAO od4=new OffreDAO();
//    Offre o4= new Offre();
//    o4=od4.rechercherOffreById(id5);
// byte[] img4=o4.getPhoto1();
// ImageIcon icon4 = new ImageIcon(img4);
//annonce5.setIcon(icon4);// 
//OffreDAO od5=new OffreDAO();
//    Offre o5= new Offre();
//    o5=od5.rechercherOffreById(id6);
// byte[] img5=o5.getPhoto1();
// ImageIcon icon5 = new ImageIcon(img5);
//annonce6.setIcon(icon5);// NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        annonce3 = new javax.swing.JButton();
        annonce4 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jSlider1 = new javax.swing.JSlider();
        annonce2 = new javax.swing.JButton();
        annonce1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        connecter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1165, 728));
        getContentPane().setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(350, 130, 80, 580);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nature");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 220, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Gouvernorat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 260, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Localité");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 300, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date Disponibilité");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 360, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Prix");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 440, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Trié par");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 520, 70, 30);

        annonce3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annonce3ActionPerformed(evt);
            }
        });
        getContentPane().add(annonce3);
        annonce3.setBounds(420, 480, 230, 150);

        annonce4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annonce4ActionPerformed(evt);
            }
        });
        getContentPane().add(annonce4);
        annonce4.setBounds(760, 480, 230, 150);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(170, 350, 87, 20);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(170, 380, 87, 20);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(110, 440, 200, 23);

        annonce2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annonce2ActionPerformed(evt);
            }
        });
        getContentPane().add(annonce2);
        annonce2.setBounds(750, 150, 230, 150);

        annonce1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annonce1ActionPerformed(evt);
            }
        });
        getContentPane().add(annonce1);
        annonce1.setBounds(390, 150, 230, 150);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Chambre", "Maison" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(170, 230, 80, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Ariana", "Tunis", "Ben Arouss", "Beja", "Nabeul", "Bizetre" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(170, 270, 80, 20);

        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(170, 310, 80, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Plus récent", "Plus Noté", "Prix croissant", "Prix décroissant" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(150, 530, 80, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/arriere plan.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -300, 1120, 1310);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 620, 120, 50);

        connecter.setText("se connecter");
        connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecterActionPerformed(evt);
            }
        });
        getContentPane().add(connecter);
        connecter.setBounds(900, 20, 180, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annonce1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annonce1ActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_annonce1ActionPerformed

    private void connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecterActionPerformed

        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_connecterActionPerformed

    private void annonce2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annonce2ActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_annonce2ActionPerformed

    private void annonce3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annonce3ActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_annonce3ActionPerformed

    private void annonce4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annonce4ActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_annonce4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                conversation c = new conversation();
                c.setVisible(true);

                c.setSize(1115, 728);
                c.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annonce1;
    private javax.swing.JButton annonce2;
    private javax.swing.JButton annonce3;
    private javax.swing.JButton annonce4;
    private javax.swing.JButton connecter;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
