/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.gui;

import com.esprit.dao.UserDAO;
import com.esprit.entities.User;
import java.awt.Color;
import java.lang.*;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author maher
 */
public class inscription extends javax.swing.JFrame {

    /**
     *
     */
    private int x = 0;

    public inscription() {
        initComponents();
        placeHolder();
    }

    public void placeHolder() {

        nom.setCaretColor(Color.GRAY);
        nom.setText("nom");
        prenom.setCaretColor(Color.GRAY);
        prenom.setText("Prenom");
        login.setCaretColor(Color.GRAY);
        login.setText("Login");
        pwd.setCaretColor(Color.GRAY);
        pwd.setText("Mot de Passe");
        email.setCaretColor(Color.GRAY);
        email.setText("@Email");
        telephone.setCaretColor(Color.GRAY);
        telephone.setText("Télephone");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Client = new javax.swing.JRadioButton();
        Annonceur = new javax.swing.JRadioButton();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        login = new javax.swing.JTextField();
        reponse = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Client.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Client.setText("Client");
        Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientActionPerformed(evt);
            }
        });
        getContentPane().add(Client);
        Client.setBounds(570, 480, 100, 30);

        Annonceur.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Annonceur.setText("Annonceur");
        Annonceur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnonceurActionPerformed(evt);
            }
        });
        getContentPane().add(Annonceur);
        Annonceur.setBounds(700, 480, 130, 30);

        nom.setToolTipText("name");
        nom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nom.setHighlighter(null);
        nom.setName(""); // NOI18N
        nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomMouseClicked(evt);
            }
        });
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom);
        nom.setBounds(554, 292, 305, 42);

        prenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prenomMouseClicked(evt);
            }
        });
        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        getContentPane().add(prenom);
        prenom.setBounds(143, 292, 305, 42);

        telephone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telephoneMouseClicked(evt);
            }
        });
        telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneActionPerformed(evt);
            }
        });
        getContentPane().add(telephone);
        telephone.setBounds(552, 372, 305, 42);

        email.setAlignmentX(0.2F);
        email.setAlignmentY(0.2F);
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(143, 373, 305, 42);

        login.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(142, 210, 305, 42);
        getContentPane().add(reponse);
        reponse.setBounds(370, 540, 420, 40);

        pwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdMouseClicked(evt);
            }
        });
        getContentPane().add(pwd);
        pwd.setBounds(554, 210, 305, 42);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Status");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 470, 90, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/formulaire inscri.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -200, 1180, 1090);

        valider.setText("jButton1");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        getContentPane().add(valider);
        valider.setBounds(360, 590, 380, 60);

        annuler.setText("jButton1");
        getContentPane().add(annuler);
        annuler.setBounds(700, 540, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientActionPerformed
        Annonceur.setSelected(false);
        x = 2;
    }//GEN-LAST:event_ClientActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed

    }//GEN-LAST:event_nomActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        User u = new User();

        u.setNom(nom.getText());
        u.setPrenom(prenom.getText());

        Pattern pattern = Pattern.compile("^[0-9]{8}$");
        Matcher m = pattern.matcher(telephone.getText());
        boolean b = m.matches();

        if (b) {
            u.setTelephone(Integer.parseInt(telephone.getText()));
        } else {
            reponse.setText("le numéro de télephone doit être composé de chiffres\n");
        }

        Pattern p2 = Pattern.compile("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9-]+)*\\.([a-z]{2,4})$");
        Matcher m2 = p2.matcher(email.getText());
        boolean b2 = m2.matches();

        if (b2) {
            u.setEmail(email.getText());
        } else {
            reponse.setText("l'email est faux\n");
        }
        if (x == 1) {
            u.setRoles("a:1:{i:0;s:14:\"ROLE_ANNONCEUR\";}");
        } else {
            u.setRoles("a:1:{i:0;s:11:\"ROLE_CLIENT\";}");
        }
        u.setUsername(login.getText());

        u.setPasswod(pwd.getText());

        if (nom.getText().isEmpty() || prenom.getText().isEmpty() || telephone.getText().isEmpty() || email.getText().isEmpty() || x == 0 || login.getText().isEmpty() || pwd.getText().isEmpty()) {
            reponse.setText(" un champ obligatoire est vide");
        }
        UserDAO ud = new UserDAO();
        if (ud.checklogin(login.getText())) {
            reponse.setText("Login existe déja");
        } else {
            ud.ajouterUser(u);
            reponse.setText("vous êtes ajouté avec succes");
            Login l = new Login();
            l.setVisible(true);
            l.setSize(1075, 748);
            l.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_validerActionPerformed

    private void telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneActionPerformed

    private void AnnonceurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnonceurActionPerformed
        Client.setSelected(false);
        x = 1;
    }//GEN-LAST:event_AnnonceurActionPerformed

    private void nomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomMouseClicked
        nom.setText("");
    }//GEN-LAST:event_nomMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

    }//GEN-LAST:event_loginActionPerformed

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed

    }//GEN-LAST:event_prenomActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        email.setText("");
    }//GEN-LAST:event_emailMouseClicked

    private void prenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prenomMouseClicked
        prenom.setText("");
    }//GEN-LAST:event_prenomMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        login.setText("");
    }//GEN-LAST:event_loginMouseClicked

    private void pwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdMouseClicked
        pwd.setText("");
    }//GEN-LAST:event_pwdMouseClicked

    private void telephoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telephoneMouseClicked
        telephone.setText("");
    }//GEN-LAST:event_telephoneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                inscription i = new inscription();
                i.setSize(1075, 708);
                i.setVisible(true);

                i.setLocationRelativeTo(null);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Annonceur;
    private javax.swing.JRadioButton Client;
    private javax.swing.JButton annuler;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JLabel reponse;
    private javax.swing.JTextField telephone;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
