/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.gui;


import Twitter.Twitter;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserAdapter;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserNavigationEvent;
import com.esprit.dao.UserDAO;
import com.esprit.entities.User;
import java.awt.BorderLayout;
import java.io.StringReader;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.html.HTMLEditorKit;
import org.fb.GraphReaderExample;

/**
 *
 * @author maher
 */
public class Login extends javax.swing.JFrame {
    public static User us=new User();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        reponse = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mot = new javax.swing.JButton();
        connecter = new javax.swing.JButton();
        inscrire = new javax.swing.JButton();
        facebook = new javax.swing.JButton();
        twitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(java.awt.Color.darkGray);
        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 380, 50));

        pwd.setBackground(java.awt.Color.darkGray);
        pwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 380, 50));
        getContentPane().add(reponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 504, 260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/Login-Form.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -150, 1430, 1040));

        mot.setText("jButton1");
        mot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                motMouseReleased(evt);
            }
        });
        mot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motActionPerformed(evt);
            }
        });
        getContentPane().add(mot, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 180, -1));

        connecter.setText("jButton1");
        connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecterActionPerformed(evt);
            }
        });
        getContentPane().add(connecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 440, 60));

        inscrire.setText("jButton2");
        inscrire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscrireMouseClicked(evt);
            }
        });
        inscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrireActionPerformed(evt);
            }
        });
        getContentPane().add(inscrire, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 670, 190, 40));

        facebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookActionPerformed(evt);
            }
        });
        getContentPane().add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 210, 40));

        twitter.setText("jButton2");
        twitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterActionPerformed(evt);
            }
        });
        getContentPane().add(twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 210, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed
public static String API_KEY = "1500144570264526";//à remplacer
  public static String SECRET = "771a6"
          + ""
          + "dfde6924911dbed42343baedbad";//à remplacer
//https://graph.facebook.com/oauth/authorize?
  public static String firstRequest = "https://web.facebook.com/darkomlocation/?fref=ts"
  + "client_id="
  + API_KEY
  + "&redirect_uri=http://www.facebook.com/connect/login_success.html&"
  + "scope=publish_stream,offline_access,create_event,read_stream,email,user_about_me,user_birthday";
  //
  public static String secondRequest="https://graph.facebook.com/oauth/access_token?"
  + "client_id="
  + API_KEY
  + "&redirect_uri=http://www.facebook.com/connect/login_success.html&"
  + "client_secret=" + SECRET + "&code=";
  public static String access_token = "";
  public static boolean firstRequestDone = false;
  public static boolean secondRequestDone = false;
    private void connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecterActionPerformed
      String l = login.getText();
      String s = pwd.getText();
      User u= new User();
      UserDAO ud=new UserDAO();
      boolean m =ud.checklogin(l);
        System.out.println("m= "+ m);
     
      if (!m)
          reponse.setText("ce  login n'existe pas");
      else{
          u=ud.findUserByLogin(l);
          System.out.println("nom= "+u.getNom());
          us=ud.findUserByLogin(l);
       if(u.getPasswod().contains(s) ) {
           if(u.getRoles().equals("a:1:{i:0;s:14:\"ROLE_ANNONCEUR\";}")){
               System.out.println("Annonceur");
           menu j = new menu();
           j.setVisible(true);
           j.setSize(1175, 728);
           j.setLocationRelativeTo(null);
           this.setVisible(false);
               }
           else if(u.getRoles().equals("a:1:{i:0;s:11:\"ROLE_CLIENT\";}"))
           {
               System.out.println("Client");
               us=ud.findUserByLogin(l);
       menuClient j = new menuClient();
           j.setVisible(true);
           j.setSize(1175, 728);
            j.setLocationRelativeTo(null);
           this.setVisible(false);}
           else if(u.getRoles().equals("a:1:{i:0;s:10:\"ROLE_ADMIN\";}"))
                   {
                       System.out.println("Admin");
                  Administrateur a= new Administrateur();
                  a.setVisible(true);
           a.setSize(1175, 728);
            a.setLocationRelativeTo(null);
           this.setVisible(false);
                   }
         
    
        }
           else {
           reponse.setText("ce mot de passe est faux");
        }
      
      }   
    }//GEN-LAST:event_connecterActionPerformed

    private void inscrireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscrireMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inscrireMouseClicked

    private void inscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrireActionPerformed
      inscription i =new inscription();
             i.setVisible(true);
             i.setSize(1370, 900);
             i.setLocationRelativeTo(null);
             this.setVisible(false);
    }//GEN-LAST:event_inscrireActionPerformed

    private void facebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookActionPerformed
      SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                NativeInterface.open();
                NativeInterface.initialize();
                final JFrame authFrame = new JFrame();
// Create the JWebBrowser and add the WebBrowserAdapter
                JPanel webBrowserPanel = new JPanel(new BorderLayout());
                final JWebBrowser webBrowser = new JWebBrowser();
                webBrowser.navigate(firstRequest);
                webBrowser.addWebBrowserListener(new WebBrowserAdapter() {
                                        public void locationChanged(WebBrowserNavigationEvent e) {
                        super.locationChanged(e);
// Check if first request was not done
                        if (!firstRequestDone) {
// Check if you left the location and were redirected to the next
// location
                            if (e.getNewResourceLocation().contains("http://www.facebook.com/connect/login_success.html?code")) {
// If it successfully redirects you, get the verification code
// and go for a second request
                                String[] splits = e.getNewResourceLocation().split("=");
                                String stage2temp = secondRequest + splits[1];
                                System.out.println("First =" + splits[1]);
                                webBrowser.navigate(stage2temp);
                                firstRequestDone = true;
                            }
                        } else {
// If secondRequest is not done yet, you perform this and get the
// access_token
                            if (!secondRequestDone) {
                                authFrame.setVisible(false);
                                System.out.println(webBrowser.getHTMLContent());
// Create reader with the html content
                                StringReader readerSTR = new StringReader(webBrowser.getHTMLContent());
// Create a callback for html parser
                                HTMLEditorKit.ParserCallback callback
                                        = new HTMLEditorKit.ParserCallback() {
                                            @Override
                                            public void handleText(char[] data, int pos) {
                                                System.out.println(data);
// because there is only one line with the access_token
// in the html content you can parse it.
                                                String string = new String(data);
                                                String[] temp1 = string.split("&");
                                                String[] temp2 = temp1[0].split("=");
                                                System.out.println("access tocken=" + temp2);
                                                access_token = temp2[1];
                                                new GraphReaderExample(access_token).runEverything();
                                                
                                                //JOptionPane.showMessageDialog(rootPane, "Veuillez ajouter les informations manquantes  ");
                                                
                                                }
//                                                
//                                         
//                                                
//
                                            
                                        };
                                
                            }
                        }
                    }
                });
                webBrowserPanel.add(webBrowser, BorderLayout.CENTER);
                authFrame.add(webBrowserPanel);
                authFrame.setSize(400, 500);
                authFrame.setVisible(true);
            
            }});
        

       
    }//GEN-LAST:event_facebookActionPerformed

    private void twitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterActionPerformed
        Twitter t = new Twitter();
        t.setSize(1175, 728);
        t.setVisible(true);
    }//GEN-LAST:event_twitterActionPerformed

    private void motMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_motMouseReleased

    private void motActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motActionPerformed
           
        UserDAO udao =new UserDAO();
        String l= login.getText();
      udao.findUserByLogin(l);
        motdepasseoublie e= new motdepasseoublie() ;  
        e.setVisible(true);
    }//GEN-LAST:event_motActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Login l= new Login();
               l.setVisible(true);
               l.setSize(1075, 748);
               l.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connecter;
    private javax.swing.JButton facebook;
    private javax.swing.JButton inscrire;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField login;
    private javax.swing.JButton mot;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JLabel reponse;
    private javax.swing.JButton twitter;
    // End of variables declaration//GEN-END:variables
}
