/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.gui;

import com.esprit.dao.OffreDAO;
import com.esprit.entities.Offre;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.UIManager;

/**
 *
 * @author pc
 */
public class menuClient extends javax.swing.JFrame {

    /**
     * Creates new form menuClient
     */
    public int result;
    int value1 = 0;
    int value2 = 0;
    int value3 = 0;
    int value4 = 0;
   public static int id_loc;

    public menuClient() {

        initComponents();
        slider.setValue(0);
        slider2.setValue(0);
        // jprix.setText("0.0");
        //jComboGouvernorat.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jretour = new javax.swing.JButton();
        slider2 = new javax.swing.JSlider();
        slider = new javax.swing.JSlider();
        jMail = new javax.swing.JButton();
        DateFin = new com.toedter.calendar.JDateChooser();
        DateDebut = new com.toedter.calendar.JDateChooser();
        jTitre3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTitre2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTitre1 = new javax.swing.JLabel();
        jPhoto2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPhoto1 = new javax.swing.JLabel();
        jTitre = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboNature = new javax.swing.JComboBox();
        jComboGouvernorat = new javax.swing.JComboBox();
        jComboLocalite = new javax.swing.JComboBox();
        jButtonModifier = new javax.swing.JButton();
        jButtonDeco = new javax.swing.JButton();
        jButtonRechercher = new javax.swing.JButton();
        jPrix = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();
        jLocalite = new javax.swing.JLabel();
        jGouvernorat = new javax.swing.JLabel();
        jNature = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jretour.setText("Retour");
        jretour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jretourMouseReleased(evt);
            }
        });
        jretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jretourActionPerformed(evt);
            }
        });
        getContentPane().add(jretour);
        jretour.setBounds(220, 600, 100, 40);

        slider2.setMajorTickSpacing(200);
        slider2.setMaximum(1000);
        slider2.setPaintLabels(true);
        slider2.setPaintTicks(true);
        slider2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                slider2MouseMoved(evt);
            }
        });
        getContentPane().add(slider2);
        slider2.setBounds(90, 410, 300, 45);

        slider.setMajorTickSpacing(200);
        slider.setMaximum(1000);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sliderMouseMoved(evt);
            }
        });
        getContentPane().add(slider);
        slider.setBounds(90, 350, 300, 45);

        jMail.setText("Contacter Annonceur");
        jMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMailMouseReleased(evt);
            }
        });
        jMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMailActionPerformed(evt);
            }
        });
        getContentPane().add(jMail);
        jMail.setBounds(470, 30, 180, 30);

        DateFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateFinMouseClicked(evt);
            }
        });
        getContentPane().add(DateFin);
        DateFin.setBounds(290, 500, 130, 30);

        DateDebut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateDebutMouseClicked(evt);
            }
        });
        getContentPane().add(DateDebut);
        DateDebut.setBounds(150, 500, 130, 30);

        jTitre3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jTitre3.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(jTitre3);
        jTitre3.setBounds(950, 460, 60, 140);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(750, 450, 190, 160);

        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(740, 440, 280, 180);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 450, 190, 160);

        jTitre2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jTitre2.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(jTitre2);
        jTitre2.setBounds(660, 460, 60, 130);

        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 440, 280, 180);

        jTitre1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jTitre1.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(jTitre1);
        jTitre1.setBounds(950, 240, 60, 130);
        getContentPane().add(jPhoto2);
        jPhoto2.setBounds(750, 220, 200, 160);

        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(740, 210, 280, 180);
        getContentPane().add(jPhoto1);
        jPhoto1.setBounds(460, 220, 180, 160);

        jTitre.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jTitre.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(jTitre);
        jTitre.setBounds(650, 230, 70, 120);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/weather_256.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(580, 70, 110, 110);

        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 210, 280, 180);

        jComboNature.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Chambre", "Maison" }));
        jComboNature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboNatureActionPerformed(evt);
            }
        });
        getContentPane().add(jComboNature);
        jComboNature.setBounds(120, 190, 160, 30);

        jComboGouvernorat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Ariana", "Beja", "Ben Arous", "Bizerte", "Gabes", "Gafsa", "Jendouba", "kairouan", "kasserine", "kebili", "Le Kef", "Mahdia", "Manouba", "Medenine", "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliane", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouane", "" }));
        jComboGouvernorat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGouvernoratActionPerformed(evt);
            }
        });
        getContentPane().add(jComboGouvernorat);
        jComboGouvernorat.setBounds(120, 230, 160, 30);

        jComboLocalite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Cité Olympique", "Manzah 9", "Mourouj", "Corniche" }));
        jComboLocalite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLocaliteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboLocalite);
        jComboLocalite.setBounds(120, 280, 160, 30);

        jButtonModifier.setText("Modifier Compte");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModifier);
        jButtonModifier.setBounds(660, 30, 120, 30);

        jButtonDeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/button_log_off_100856.jpg"))); // NOI18N
        jButtonDeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeco);
        jButtonDeco.setBounds(990, 10, 50, 50);

        jButtonRechercher.setText("Rechercher");
        jButtonRechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonRechercherMouseReleased(evt);
            }
        });
        jButtonRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechercherActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRechercher);
        jButtonRechercher.setBounds(80, 600, 100, 40);

        jPrix.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jPrix.setText("Prix");
        getContentPane().add(jPrix);
        jPrix.setBounds(10, 390, 50, 30);

        jDate.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jDate.setText("Date Disponibilité");
        getContentPane().add(jDate);
        jDate.setBounds(10, 497, 120, 30);

        jLocalite.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLocalite.setText("Localité");
        getContentPane().add(jLocalite);
        jLocalite.setBounds(10, 280, 80, 30);

        jGouvernorat.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jGouvernorat.setText("Gouvernorat");
        getContentPane().add(jGouvernorat);
        jGouvernorat.setBounds(10, 234, 100, 20);

        jNature.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jNature.setText("Nature");
        getContentPane().add(jNature);
        jNature.setBounds(10, 190, 80, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/arriere plan.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 820);

        setSize(new java.awt.Dimension(1058, 786));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRechercherActionPerformed

    private void jButtonRechercherMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRechercherMouseReleased

        OffreDAO od = new OffreDAO();
        Offre o = new Offre();

        int choix;
        if (jComboNature.getSelectedIndex() != 0) {
            
            
            
            choix = jComboNature.getSelectedIndex();
            int nature = 9;

            List<String> id = new ArrayList<String>();
            System.out.println(id);

            switch (choix) {
                case 1:

                    nature = 0;
                    break;
                case 2:

                    nature = 1;
                    break;

            }

            id = od.rechercherOffreByType(nature);

            jTitre.setText(null);
            jPhoto1.setIcon(null);
            jTitre1.setText(null);
            jPhoto2.setIcon(null);
            jTitre2.setText(null);
            jLabel3.setIcon(null);
            jTitre3.setText(null);
            jLabel4.setIcon(null);

            for (int i = 0; i < id.size(); i++) {

                if (i == 0) {
                    Offre o1 = new Offre();
                    String titre1 = od.trouverTitreById(Integer.parseInt(id.get(0)));
                    jTitre.setText(titre1);
                    o1 = od.rechercherOffreById(Integer.parseInt(id.get(0)));
                    byte[] img1 = o1.getPhoto1();
                    ImageIcon icon1 = new ImageIcon(img1);
                    jPhoto1.setIcon(icon1);
                }
         
                if (i == 1) {
                    Offre o2 = new Offre();
                    String titre2 = od.trouverTitreById(Integer.parseInt(id.get(1)));
                    jTitre1.setText(titre2);
                    o2 = od.rechercherOffreById(Integer.parseInt(id.get(1)));
                    byte[] img2 = o2.getPhoto1();
                    ImageIcon icon2 = new ImageIcon(img2);
                    jPhoto2.setIcon(icon2);
                }
                if (i == 2) {
                    Offre o3 = new Offre();
                    String titre3 = od.trouverTitreById(Integer.parseInt(id.get(2)));
                    jTitre2.setText(titre3);
                    o3 = od.rechercherOffreById(Integer.parseInt(id.get(2)));
                    byte[] img3 = o3.getPhoto1();
                    ImageIcon icon3 = new ImageIcon(img3);
                    jLabel3.setIcon(icon3);
                }
                if (i == 3) {
                    Offre o4 = new Offre();
                    String titre4 = od.trouverTitreById(Integer.parseInt(id.get(3)));
                    jTitre3.setText(titre4);
                    o4 = od.rechercherOffreById(Integer.parseInt(id.get(3)));
                    byte[] img4 = o4.getPhoto1();
                    ImageIcon icon4 = new ImageIcon(img4);
                    jLabel4.setIcon(icon4);
                }
            }

        } else if (jComboGouvernorat.getSelectedIndex() != 0) {
            choix = jComboGouvernorat.getSelectedIndex();
            List<String> id1 = new ArrayList<String>();

            String gouvernorat = null;
            switch (choix) {
                case 1:
                    gouvernorat = "Ariana";
                    break;
                case 2:
                    gouvernorat = "Beja";
                    break;
                case 3:
                    gouvernorat = "Ben Arous";
                    break;
                case 4:
                    gouvernorat = "Bizerte";
                    break;
                case 5:
                    gouvernorat = "Gabes";
                    break;
                case 6:
                    gouvernorat = "Gafsa";
                    break;
                case 7:
                    gouvernorat = "Jendouba";
                    break;
                case 8:
                    gouvernorat = "kairouan";
                    break;
                case 9:
                    gouvernorat = " kasserine ";
                    break;
                case 10:
                    gouvernorat = "kebili";
                    break;
                case 11:
                    gouvernorat = "le kef";
                    break;
                case 12:
                    gouvernorat = "Mahdia";
                    break;
                case 13:
                    gouvernorat = "Manouba";
                    break;
                case 14:
                    gouvernorat = "Medenine";
                    break;
                case 15:
                    gouvernorat = "Monastir";
                    break;
                case 16:
                    gouvernorat = "Nabeul";
                    break;
                case 17:
                    gouvernorat = "Sfax";
                    break;
                case 18:
                    gouvernorat = "Sidi Bouzid";
                    break;
                case 19:
                    gouvernorat = " Siliane";
                    break;
                case 20:
                    gouvernorat = "Sousse";
                    break;
                case 21:
                    gouvernorat = " Tataouine";
                    break;
                case 22:
                    gouvernorat = "  Tozeur";
                    break;
                case 23:
                    gouvernorat = "Tunis";
                    break;
                case 24:
                    gouvernorat = "zaghouene";
                    break;

                default:
                    gouvernorat = "";

            }

            id1 = od.rechercherOffreByGouvernorat(gouvernorat);
            jTitre.setText(null);
            jPhoto1.setIcon(null);
            jTitre1.setText(null);
            jPhoto2.setIcon(null);
            jTitre2.setText(null);
            jLabel3.setIcon(null);
            jTitre3.setText(null);
            jLabel4.setIcon(null);

            for (int i = 0; i < id1.size(); i++) {
                if (i == 0) {
                    int value1 = Integer.parseInt(id1.get(0));
                    Offre o1 = new Offre();
                    String titre1 = od.trouverTitreById(value1);
                    jTitre.setText(titre1);
                    o1 = od.rechercherOffreById(value1);
                    byte[] img1 = o1.getPhoto1();
                    ImageIcon icon1 = new ImageIcon(img1);
                    jPhoto1.setIcon(icon1);
                }
                if (i == 1) {
                    int value2 = Integer.parseInt(id1.get(1));
                    Offre o2 = new Offre();
                    String titre2 = od.trouverTitreById(value2);
                    jTitre1.setText(titre2);
                    o2 = od.rechercherOffreById(value2);
                    byte[] img2 = o2.getPhoto1();
                    ImageIcon icon2 = new ImageIcon(img2);
                    jPhoto2.setIcon(icon2);
                }
                if (i == 2) {
                    int value3 = Integer.parseInt(id1.get(2));
                    Offre o3 = new Offre();
                    String titre3 = od.trouverTitreById(value3);
                    jTitre2.setText(titre3);
                    o3 = od.rechercherOffreById(value3);
                    byte[] img3 = o3.getPhoto1();
                    ImageIcon icon3 = new ImageIcon(img3);
                    jLabel3.setIcon(icon3);
                }
                if (i == 3) {
                    int value4 = Integer.parseInt(id1.get(3));
                    Offre o4 = new Offre();
                    String titre4 = od.trouverTitreById(value4);
                    jTitre3.setText(titre4);
                    o4 = od.rechercherOffreById(value4);
                    byte[] img4 = o4.getPhoto1();
                    ImageIcon icon4 = new ImageIcon(img4);
                    jLabel4.setIcon(icon4);
                }
            }

            // System.out.println(gouvernorat);
        } else if (jComboLocalite.getSelectedIndex() != 0) {
            choix = jComboLocalite.getSelectedIndex();
            String localite = "manzah";

            List<String> id2 = new ArrayList<String>();

            switch (choix) {
                case 1:

                    localite = "Cité Olympique";

                    break;
                case 2:

                    localite = "Manzah 9";
                    break;

                case 3:

                    localite = "Mourouj";
                    break;

                case 4:

                    localite = "Corniche";
                    break;
            }
            id2 = od.rechercherOffreByLocalite(localite);
            jTitre.setText(null);
            jPhoto1.setIcon(null);
            jTitre1.setText(null);
            jPhoto2.setIcon(null);
            jTitre2.setText(null);
            jLabel3.setIcon(null);
            jTitre3.setText(null);
            jLabel4.setIcon(null);

            for (int i = 0; i < id2.size(); i++) {
                if (i == 0) {
                    int value1 = Integer.parseInt(id2.get(0));
                    Offre o1 = new Offre();
                    String titre1 = od.trouverTitreById(value1);
                    jTitre.setText(titre1);
                    o1 = od.rechercherOffreById(value1);
                    byte[] img1 = o1.getPhoto1();
                    ImageIcon icon1 = new ImageIcon(img1);
                    jPhoto1.setIcon(icon1);
                }
                if (i == 1) {
                    int value2 = Integer.parseInt(id2.get(1));
                    Offre o2 = new Offre();
                    String titre2 = od.trouverTitreById(value2);
                    jTitre1.setText(titre2);
                    o2 = od.rechercherOffreById(value2);
                    byte[] img2 = o2.getPhoto1();
                    ImageIcon icon2 = new ImageIcon(img2);
                    jPhoto2.setIcon(icon2);
                }
                if (i == 2) {
                    int value3 = Integer.parseInt(id2.get(2));
                    Offre o3 = new Offre();
                    String titre3 = od.trouverTitreById(value3);
                    jTitre2.setText(titre3);
                    o3 = od.rechercherOffreById(value3);
                    byte[] img3 = o3.getPhoto1();
                    ImageIcon icon3 = new ImageIcon(img3);
                    jLabel3.setIcon(icon3);
                }
                if (i == 3) {
                    int value4 = Integer.parseInt(id2.get(3));
                    Offre o4 = new Offre();
                    String titre4 = od.trouverTitreById(value4);
                    jTitre3.setText(titre4);
                    o4 = od.rechercherOffreById(value4);
                    byte[] img4 = o4.getPhoto1();
                    ImageIcon icon4 = new ImageIcon(img4);
                    jLabel4.setIcon(icon4);
                }
            }
        } else if (slider.getValue() != 0 && slider2.getValue() != 0) {
            jTitre.setText(null);
            jPhoto1.setIcon(null);
            jTitre1.setText(null);
            jPhoto2.setIcon(null);
            jTitre2.setText(null);
            jLabel3.setIcon(null);
            jTitre3.setText(null);
            jLabel4.setIcon(null);

            if (slider2.getValue() - slider.getValue() > 0) {

                List<String> id4 = new ArrayList<String>();
                OffreDAO ud = new OffreDAO();
                //jslider.setText(String.valueOf(slider.getValue()));
                float p1 = (float) slider.getValue();
                float p2 = (float) slider2.getValue();

                System.out.println(p1);
                System.out.println(p2);
                id4 = ud.rechercherOffreByPrix(p1, p2);

                for (int i = 0; i < id4.size(); i++) {
                    if (i == 0) {
                        int value1 = Integer.parseInt(id4.get(0));
                        Offre o1 = new Offre();
                        String titre1 = od.trouverTitreById(value1);
                        jTitre.setText(titre1);
                        o1 = od.rechercherOffreById(value1);
                        byte[] img1 = o1.getPhoto1();
                        ImageIcon icon1 = new ImageIcon(img1);
                        jPhoto1.setIcon(icon1);
                    }
                    if (i == 1) {
                        int value2 = Integer.parseInt(id4.get(1));
                        Offre o2 = new Offre();
                        String titre2 = od.trouverTitreById(value2);
                        jTitre1.setText(titre2);
                        o2 = od.rechercherOffreById(value2);
                        byte[] img2 = o2.getPhoto1();
                        ImageIcon icon2 = new ImageIcon(img2);
                        jPhoto2.setIcon(icon2);
                    }
                    if (i == 2) {
                        int value3 = Integer.parseInt(id4.get(2));
                        Offre o3 = new Offre();
                        String titre3 = od.trouverTitreById(value3);
                        jTitre2.setText(titre3);
                        o3 = od.rechercherOffreById(value3);
                        byte[] img3 = o3.getPhoto1();
                        ImageIcon icon3 = new ImageIcon(img3);
                        jLabel3.setIcon(icon3);
                    }
                    if (i == 3) {
                        int value4 = Integer.parseInt(id4.get(3));
                        Offre o4 = new Offre();
                        String titre4 = od.trouverTitreById(value4);
                        jTitre3.setText(titre4);
                        o4 = od.rechercherOffreById(value4);
                        byte[] img4 = o4.getPhoto1();
                        ImageIcon icon4 = new ImageIcon(img4);
                        jLabel4.setIcon(icon4);
                    }
                }
            }
        } else if (DateDebut != null && DateFin != null) {
            jTitre.setText(null);
            jPhoto1.setIcon(null);
            jTitre1.setText(null);
            jPhoto2.setIcon(null);
            jTitre2.setText(null);
            jLabel3.setIcon(null);
            jTitre3.setText(null);
            jLabel4.setIcon(null);
            java.util.Date dt1, dt2;
            dt2 = DateFin.getDate();
            dt1 = DateDebut.getDate();
            if (dt1.before(dt2)) {
                List<String> id3 = new ArrayList<String>();

                java.sql.Date d1 = new java.sql.Date(dt1.getTime());
                java.sql.Date d2 = new java.sql.Date(dt2.getTime());

                OffreDAO ud = new OffreDAO();
                id3 = ud.rechercherOffreByDate(d1, d2);

                for (int i = 0; i < id3.size(); i++) {
                    if (i == 0) {
                        int value1 = Integer.parseInt(id3.get(0));
                        Offre o1 = new Offre();
                        String titre1 = od.trouverTitreById(value1);
                        jTitre.setText(titre1);
                        o1 = od.rechercherOffreById(value1);
                        byte[] img1 = o1.getPhoto1();
                        ImageIcon icon1 = new ImageIcon(img1);
                        jPhoto1.setIcon(icon1);
                    }
                    if (i == 1) {
                        int value2 = Integer.parseInt(id3.get(1));
                        Offre o2 = new Offre();
                        String titre2 = od.trouverTitreById(value2);
                        jTitre1.setText(titre2);
                        o2 = od.rechercherOffreById(value2);
                        byte[] img2 = o2.getPhoto1();
                        ImageIcon icon2 = new ImageIcon(img2);
                        jPhoto2.setIcon(icon2);
                    }
                    if (i == 2) {
                        int value3 = Integer.parseInt(id3.get(2));
                        Offre o3 = new Offre();
                        String titre3 = od.trouverTitreById(value3);
                        jTitre2.setText(titre3);
                        o3 = od.rechercherOffreById(value3);
                        byte[] img3 = o3.getPhoto1();
                        ImageIcon icon3 = new ImageIcon(img3);
                        jLabel3.setIcon(icon3);
                    }
                    if (i == 3) {
                        int value4 = Integer.parseInt(id3.get(3));
                        Offre o4 = new Offre();
                        String titre4 = od.trouverTitreById(value4);
                        jTitre3.setText(titre4);
                        o4 = od.rechercherOffreById(value4);
                        byte[] img4 = o4.getPhoto1();
                        ImageIcon icon4 = new ImageIcon(img4);
                        jLabel4.setIcon(icon4);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "veuillez resaisir la date de recherche");
            }
        }


    }//GEN-LAST:event_jButtonRechercherMouseReleased

    private void jButtonDecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecoActionPerformed
        Login j = new Login();
        j.setVisible(true);
        j.setSize(1175, 728);
        j.setLocationRelativeTo(null);

        this.setVisible(false);
    }//GEN-LAST:event_jButtonDecoActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed

        ModifierCompteClient2 j = new ModifierCompteClient2();
        j.setVisible(true);
        j.setSize(1175, 728);
        j.setLocationRelativeTo(null);

        this.setVisible(false);


    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jComboNatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboNatureActionPerformed
         jComboGouvernorat.setEnabled(false);
            jComboLocalite.setEnabled(false);
            slider.setEnabled(false);
            slider2.setEnabled(false);
            DateDebut.setEnabled(false);
            DateFin.setEnabled(false);
    }//GEN-LAST:event_jComboNatureActionPerformed

    private void jComboGouvernoratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGouvernoratActionPerformed
            jComboNature.setEnabled(false);
            jComboLocalite.setEnabled(false);
            slider.setEnabled(false);
            slider2.setEnabled(false);
            DateDebut.setEnabled(false);
            DateFin.setEnabled(false);
    }//GEN-LAST:event_jComboGouvernoratActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        OffreDAO off = new OffreDAO();
        
        System.out.println(jTitre.getText());
        id_loc=off.trouverIdbyTitre(jTitre.getText());
        détails_offre d = new détails_offre();
        d.setVisible(true);
        d.setSize(1175, 728);
        d.setLocationRelativeTo(null);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMailActionPerformed
        EnvoieMail j = new EnvoieMail();
        j.setVisible(true);
       
        j.setSize(1075 , 728);
        j.setLocationRelativeTo(null);

        this.setVisible(false);
    }//GEN-LAST:event_jMailActionPerformed

    private void jMailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMailMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jMailMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        OffreDAO off = new OffreDAO();
        
        System.out.println(jTitre1.getText());
        id_loc=off.trouverIdbyTitre(jTitre1.getText());
        détails_offre d = new détails_offre();
        d.setVisible(true);
        d.setSize(1175, 728);
        d.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sliderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderMouseMoved
//            jComboNature.setEnabled(false);    
//            jComboGouvernorat.setEnabled(false);
//            jComboLocalite.setEnabled(false);
//            
//            DateDebut.setEnabled(false);
//            DateFin.setEnabled(false);
    }//GEN-LAST:event_sliderMouseMoved

    private void slider2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider2MouseMoved
//        jComboNature.setEnabled(false);    
//            jComboGouvernorat.setEnabled(false);
//            jComboLocalite.setEnabled(false);
//            
//            DateDebut.setEnabled(false);
//            DateFin.setEnabled(false);
                                    
    }//GEN-LAST:event_slider2MouseMoved

    private void jComboLocaliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLocaliteActionPerformed
        jComboGouvernorat.setEnabled(false);
            jComboNature.setEnabled(false);
            slider.setEnabled(false);
            slider2.setEnabled(false);
            DateDebut.setEnabled(false);
            DateFin.setEnabled(false);
    }//GEN-LAST:event_jComboLocaliteActionPerformed

    private void DateDebutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateDebutMouseClicked
        jComboNature.setEnabled(false);    
            jComboGouvernorat.setEnabled(false);
            jComboLocalite.setEnabled(false);
            slider.setEnabled(false);
            slider2.setEnabled(false);
            
            
                                     
    }//GEN-LAST:event_DateDebutMouseClicked

    private void DateFinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateFinMouseClicked
        jComboNature.setEnabled(false);    
            jComboGouvernorat.setEnabled(false);
            jComboLocalite.setEnabled(false);
            slider.setEnabled(false);
            slider2.setEnabled(false);
    }//GEN-LAST:event_DateFinMouseClicked

    private void jretourMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jretourMouseReleased
         menuClient j = new menuClient();
        j.setVisible(true);
        j.setSize(1075 , 728);
        j.setLocationRelativeTo(null);

        this.setVisible(false);
    }//GEN-LAST:event_jretourMouseReleased

    private void jretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jretourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jretourActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      weather w =new weather();
                w.setVisible(true);
                w.setSize(400,340);
                w.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     OffreDAO off = new OffreDAO();
        
        System.out.println(jTitre2.getText());
        id_loc=off.trouverIdbyTitre(jTitre2.getText());
        détails_offre d = new détails_offre();
        d.setVisible(true);
        d.setSize(1175, 728);
        d.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      OffreDAO off = new OffreDAO();
        
        System.out.println(jTitre3.getText());
        id_loc=off.trouverIdbyTitre(jTitre3.getText());
        détails_offre d = new détails_offre();
        d.setVisible(true);
        d.setSize(1175, 728);
        d.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }

                UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              menuClient menu=  new menuClient();
              menu.setVisible(true);
              menu.setSize(1075,728);
              menu.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateDebut;
    private com.toedter.calendar.JDateChooser DateFin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonDeco;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRechercher;
    private javax.swing.JComboBox jComboGouvernorat;
    private javax.swing.JComboBox jComboLocalite;
    private javax.swing.JComboBox jComboNature;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jGouvernorat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLocalite;
    private javax.swing.JButton jMail;
    private javax.swing.JLabel jNature;
    private javax.swing.JLabel jPhoto1;
    private javax.swing.JLabel jPhoto2;
    private javax.swing.JLabel jPrix;
    private javax.swing.JLabel jTitre;
    private javax.swing.JLabel jTitre1;
    private javax.swing.JLabel jTitre2;
    private javax.swing.JLabel jTitre3;
    private javax.swing.JButton jretour;
    private javax.swing.JSlider slider;
    private javax.swing.JSlider slider2;
    // End of variables declaration//GEN-END:variables
}
