/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.gui;

import com.esprit.dao.UserDAO;
import com.esprit.entities.User;
import static com.esprit.gui.Login.us;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author pc
 */
public class modifier_compte_annon extends javax.swing.JFrame {

    /**
     * Creates new form modifier_compte_annon
     */
    public modifier_compte_annon() {
        initComponents();
        nom.setText(us.getNom());
        prenom.setText(us.getPrenom());
        telephone.setText("" + us.getTelephone());
        email.setText(us.getEmail());
        pwd.setText("");

    }
    public static boolean isInteger(String s) {

        boolean v = false;
        try {
            Integer.parseInt(s);
            v = true;
        } catch (Exception e) {
            v = false;
        }
        return v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        valider = new javax.swing.JButton();
        pwd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deconnecter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(nom);
        nom.setBounds(470, 170, 300, 50);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(114, 434, 460, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Nom:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 180, 80, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("telephone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 300, 130, 50);
        getContentPane().add(prenom);
        prenom.setBounds(470, 230, 300, 50);
        getContentPane().add(telephone);
        telephone.setBounds(480, 290, 300, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setText("mot de passe");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 440, 140, 50);

        valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/tick.png"))); // NOI18N
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                validerMouseReleased(evt);
            }
        });
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        getContentPane().add(valider);
        valider.setBounds(690, 550, 130, 130);
        getContentPane().add(pwd);
        pwd.setBounds(480, 440, 300, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/4.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 590, 103, 90);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(480, 370, 300, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 370, 110, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("prenom");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 230, 80, 50);

        deconnecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/button_log_off_100856.jpg"))); // NOI18N
        deconnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deconnecterMouseReleased(evt);
            }
        });
        deconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnecterActionPerformed(evt);
            }
        });
        getContentPane().add(deconnecter);
        deconnecter.setBounds(1010, 30, 60, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/arriere plan.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1120, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void validerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseReleased

      String n = nom.getText();

        String p = prenom.getText();

        String h = telephone.getText();

       
        String mail = email.getText();

        String pass = pwd.getText();

        User u = new User();

        UserDAO ud = new UserDAO();
        int k = ud.findIdUserByLogin(us.getUsername());

    

        if (n.equals("")||p.equals("")||h.equals("")||mail.equals("")||pass.equals("")) {
           
           jLabel8.setText(" un champ obligatoire est vide");}
        else if (isInteger(nom.getText())||isInteger(prenom.getText())){
            
       jLabel8.setText(" nom et prenom  doivent contiennent des charactéres ");}
        
        
        else {
            Pattern p2 = Pattern.compile("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9-]+)*\\.([a-z]{2,4})$");
            Matcher m2 = p2.matcher(mail);
            boolean b2 = m2.matches();
//     

            if (b2) {
                u.setEmail(email.getText());
                
                Pattern pattern = Pattern.compile("^[0-9]{8}$");
        Matcher m = pattern.matcher(h);
        boolean b = m.matches();
                if (b) {
                      u.setTelephone(Integer.parseInt(telephone.getText()));
                     u.setNom(n);
                    u.setPrenom(p);
  u.setPasswod(pass);
  
  int confirm = JOptionPane.showConfirmDialog(this, "Etes vous sur de modifier votre compte!!!", "Confirmation", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null);
        if (confirm == JOptionPane.OK_OPTION) {
            
              ud.modifierUser(u, k);
                   
                 
                    
 JOptionPane.showMessageDialog(rootPane, " compte modifié");
              

                   
        }
                }
             else {
               jLabel8.setText("le numéro de télephone doit être composé de 8 chiffres");
            }
            }
             else {
            jLabel8.setText("verifier votre email");
        }
                        
    }                                    


    }//GEN-LAST:event_validerMouseReleased

    private void deconnecterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconnecterMouseReleased
        Login j = new Login();
        j.setVisible(true);
        j.setSize(1370, 900);

        this.setVisible(false);
    }//GEN-LAST:event_deconnecterMouseReleased

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validerActionPerformed

    private void deconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnecterActionPerformed
        // TODO add your handling code here:
        
        
        
        
//         InputStream in;
//                    try {
//                        in = new FileInputStream(new File("‪C:\\Claro.wav"));
//                        AudioStream audios = new AudioStream(in);
//                        AudioPlayer.player.start(audios);
//                    } catch (Exception ex) {
//                        JOptionPane.showMessageDialog(null, ex);
//
//                    }
//            
        
        
        
        
        Login menu = new Login() ;
       menu.setVisible(true);
       menu.setSize(1175, 728);
       menu.setLocationRelativeTo(null);
       this.setVisible(false);
    }//GEN-LAST:event_deconnecterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu menu = new menu() ;
       menu.setVisible(true);
       menu.setLocationRelativeTo(null);
       menu.setSize(1175, 728);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifier_compte_annon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifier_compte_annon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifier_compte_annon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifier_compte_annon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                modifier_compte_annon an = new modifier_compte_annon();
                an.setVisible(true);
                an.setSize(1175, 728);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deconnecter;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField pwd;
    private javax.swing.JTextField telephone;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables

}
