/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.gui;

import com.esprit.dao.UserDAO;
import com.esprit.entities.User;
import com.esprit.gui.Login;
import static com.esprit.gui.Login.us;
//import static com.esprit.gui.Login.us;
import com.sun.security.ntlm.Client;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author pc
 */
public class ModifierCompteClient2 extends javax.swing.JFrame {

    



    /**
     * Creates new form ModifierCompteClient2
     */
    
    
    public ModifierCompteClient2() {
        
        initComponents();
        jNom.setText(us.getNom());
        jPrenom.setText(us.getPrenom());
        jTelephone.setText(""+us.getTelephone());
        jEmail.setText(us.getEmail());
        jPwd.setText("");
        

          
           
        
           
        
        
    }
public static boolean isInteger (String s){
    boolean v=false;
    try{
        Integer.parseInt(s);
        v=true;
        
    }catch(Exception e){
        v=false;
    }
    return v;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        erreur = new javax.swing.JLabel();
        jNom = new javax.swing.JTextField();
        jPrenom = new javax.swing.JTextField();
        jTelephone = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jPwd = new javax.swing.JTextField();
        jValider = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRetour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(erreur);
        erreur.setBounds(170, 524, 380, 80);

        jNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNomMouseClicked(evt);
            }
        });
        jNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomActionPerformed(evt);
            }
        });
        getContentPane().add(jNom);
        jNom.setBounds(300, 150, 200, 30);

        jPrenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPrenomMouseClicked(evt);
            }
        });
        getContentPane().add(jPrenom);
        jPrenom.setBounds(300, 220, 200, 30);

        jTelephone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTelephoneMouseClicked(evt);
            }
        });
        jTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelephoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTelephone);
        jTelephone.setBounds(300, 290, 200, 30);

        jEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEmailMouseClicked(evt);
            }
        });
        getContentPane().add(jEmail);
        jEmail.setBounds(300, 350, 200, 30);

        jPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPwdMouseClicked(evt);
            }
        });
        jPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwdActionPerformed(evt);
            }
        });
        getContentPane().add(jPwd);
        jPwd.setBounds(300, 420, 200, 30);

        jValider.setText("valider");
        jValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jValiderMouseReleased(evt);
            }
        });
        jValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValiderActionPerformed(evt);
            }
        });
        getContentPane().add(jValider);
        jValider.setBounds(710, 640, 120, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 150, 40, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Prenom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 210, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Telephone");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 284, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 354, 50, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Mot de passe");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 424, 100, 20);

        jRetour.setText("Retour");
        jRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRetourMouseReleased(evt);
            }
        });
        jRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetourActionPerformed(evt);
            }
        });
        getContentPane().add(jRetour);
        jRetour.setBounds(500, 640, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/arriere plan.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 1170, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwdActionPerformed

    
    /*public static boolean isValid(String email)
{
	if( email!=null && email.trim().length()>0 )
		return email.matches("^[a-zA-Z0-9\\.\\-\\_]+@([a-zA-Z0-9\\-\\_\\.]+\\.)+([a-zA-Z]{2,4})$");
	return false;
}*/
    private void jValiderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValiderMouseReleased
        String n = jNom.getText();
        String p = jPrenom.getText();
        String h = jTelephone.getText();
       String email =jEmail.getText();
        String pass = jPwd.getText();
        User u = new User();
        
        UserDAO ud = new UserDAO();
        int k = ud.findIdUserByLogin(us.getUsername());
        
        
        
        
        if (n.equals("")||p.equals("")||h.equals("")||jEmail.equals("")||pass.equals("")) {
           
            erreur.setText(" un champ obligatoire est vide");}
        else if (isInteger(jNom.getText())||isInteger(jPrenom.getText())){
            
        erreur.setText(" nom et prenom  doivent contiennent des charactéres ");}
        
        
        else {
            Pattern pattern = Pattern.compile("^[0-9]{8}$");
        Matcher m = pattern.matcher(h);
        boolean b = m.matches();
        
            if (!b) {
                
                erreur.setText("le numéro de télephone doit être composé de 8 chiffres");
               }
            else {
                Pattern p2 = Pattern.compile("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9-]+)*\\.([a-z]{2,4})$");
                Matcher m2 = p2.matcher(email);
                boolean b2 = m2.matches();
            
            
             if (!b2) {
                     erreur.setText("verifier votre email");
                   

                }
             else {
                    u.setTelephone(Integer.parseInt(h));
                    u.setNom(n);
                    u.setPrenom(p);
                    u.setPasswod(pass);
                    u.setEmail(email);

                    int confirm = JOptionPane.showConfirmDialog(this, "Etes vous sur de modifier votre compte!!!", "Confirmation", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null);
                    if (confirm == JOptionPane.OK_OPTION) {
                    ud.modifierUser(u, k);}
                
            }
            
//             else {
////                erreur.setText("le numéro de télephone doit être composé de 8 chiffres");
//            
//        }
                        
    }                  

        }
    }//GEN-LAST:event_jValiderMouseReleased

    private void jNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomActionPerformed

    private void jTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelephoneActionPerformed

    private void jRetourMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRetourMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jRetourMouseReleased

    private void jRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetourActionPerformed
        menuClient j = new menuClient();
            j.setVisible(true);
            j.setSize(1075 , 728);
            
         this.setVisible(false);
    }//GEN-LAST:event_jRetourActionPerformed

    private void jValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValiderActionPerformed

    private void jNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNomMouseClicked
        jNom.setText(null);
    }//GEN-LAST:event_jNomMouseClicked

    private void jPrenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrenomMouseClicked
        jPrenom.setText(null);
    }//GEN-LAST:event_jPrenomMouseClicked

    private void jTelephoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTelephoneMouseClicked
        jTelephone.setText(null);
    }//GEN-LAST:event_jTelephoneMouseClicked

    private void jEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmailMouseClicked
        jEmail.setText(null);
    }//GEN-LAST:event_jEmailMouseClicked

    private void jPwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPwdMouseClicked
       jPwd.setText(null);
    }//GEN-LAST:event_jPwdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//               
                UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierCompteClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierCompteClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierCompteClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierCompteClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifierCompteClient2 j = new ModifierCompteClient2();
            j.setVisible(true);
            j.setSize(1075 , 728);
            j.setLocationRelativeTo(null);
            
         
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel erreur;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNom;
    private javax.swing.JTextField jPrenom;
    private javax.swing.JTextField jPwd;
    private javax.swing.JButton jRetour;
    private javax.swing.JTextField jTelephone;
    private javax.swing.JButton jValider;
    // End of variables declaration//GEN-END:variables
}
