/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.gui;
import com.teknikindustries.yahooweather.WeatherDisplay;
import com.teknikindustries.yahooweather.WeatherDoc;

//cloudy
//        sunny
//cold
//partly cloudy

/**
 *
 * @author maher
 */
public class weather extends javax.swing.JFrame {

    /**
     * Creates new form weather
     */
    public weather() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ville = new javax.swing.JComboBox();
        temperature = new javax.swing.JLabel();
        humidité = new javax.swing.JLabel();
        condition = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vitesse = new javax.swing.JLabel();
        visibilité = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ville.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ariana", "bizerte", "Gafsa", "nabeul" }));
        ville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villeActionPerformed(evt);
            }
        });
        getContentPane().add(ville);
        ville.setBounds(130, 30, 110, 20);
        getContentPane().add(temperature);
        temperature.setBounds(160, 70, 77, 17);
        getContentPane().add(humidité);
        humidité.setBounds(160, 150, 80, 20);
        getContentPane().add(condition);
        condition.setBounds(150, 110, 80, 20);

        jLabel2.setText("Température");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 80, 20);

        jLabel3.setText("Condition");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 80, 20);

        jLabel4.setText("Humidité");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 70, 20);

        jLabel5.setText("Pression");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 70, 20);

        jLabel6.setText("Vitesse du vent");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 240, 100, 20);
        getContentPane().add(vitesse);
        vitesse.setBounds(150, 240, 70, 20);
        getContentPane().add(visibilité);
        visibilité.setBounds(150, 190, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/safia.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void villeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villeActionPerformed
      
        
        
        int a=ville.getSelectedIndex();
      WeatherDisplay disp = new WeatherDisplay();
      if(a==0)
      {
       WeatherDoc doc =new WeatherDoc("1441893","c");
   
    
      }
      else if(a==1)
        {
       WeatherDoc doc =new WeatherDoc("1442020","c");
   
      }  
      else if(a==2)
           {
       WeatherDoc doc =new WeatherDoc("1442300","c");
   
      }
      else  {
       WeatherDoc doc =new WeatherDoc("1442475","c");
    
 
      }
      temperature.setText(disp .getTemperature()+"°C");     
      condition.setText(disp.getCondition());
      humidité.setText(disp.getHumidity()+"%");
      visibilité.setText(disp.getPressure()+disp.getPressureUnit());
      vitesse.setText(disp.getWindSpeed()+disp.getSpeedUnit());
    }//GEN-LAST:event_villeActionPerformed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(weather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(weather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(weather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(weather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                weather w =new weather();
                w.setVisible(true);
                w.setSize(400,340);
                w.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel condition;
    private javax.swing.JLabel humidité;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel temperature;
    private javax.swing.JComboBox ville;
    private javax.swing.JLabel visibilité;
    private javax.swing.JLabel vitesse;
    // End of variables declaration//GEN-END:variables
}







